# Base Image
FROM debian:latest

# Install WireGuard and necessary dependencies
RUN apt update && \
    apt install -y wireguard iproute2 qrencode iptables && \
    apt clean

# Expose WireGuard's default port (UDP 51820)
EXPOSE 51820/udp

# Copy entrypoint script to container
COPY entrypoint.sh /usr/local/bin/

# Make the script executable
RUN chmod +x /usr/local/bin/entrypoint.sh

# Set entrypoint to the script, runs WireGuard in foreground
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
